baseURL = "https://blog.grav.cn"
title = "Grav万有引力"
# for smart copyright line, leave this blank and check [params.copyright]
copyright = ""

theme = "minimo"

disqusShortname = ""
googleAnalytics = ""

Paginate = 8
preserveTaxonomyNames = true

enableRobotsTXT = true # generate robots.txt

# Syntax Highlighting ( https://gohugo.io/content-management/syntax-highlighting/ )
pygmentsCodefences = true

enableEmoji = false

# Missing translations will default to this content language
defaultContentLanguage = "zh"

[params.info]
description = "一个程序员的博客 Note for Life"
title404 = "Nothing is here!"

[params.assets]
favicon = "/img/icon.png"
gopher = "" # used in 404 template ( Generator: https://gopherize.me )

[params.copyright]
prefix = ""
holder = "Jneeee"
startYear = "2018"
suffix = ""

[params.settings]
# date & time format: https://golang.org/pkg/time/
dateFormat = "2006, Jan 02"
listDateFormat = "2006, Jan 02"
archiveDateFormat = "Jan 02"
hideEntryNavigation = ["page"] # boolean / array of sections
hideEntryMeta = ["page"] # boolean / array of sections
showReadingTime = true
showLastmod = true
taxonomyCloudShuffle = true
accentColor = "#ffcd00"
# hideMainMenu = true

[params.sidebar]
enable = false

[sidebar_menu]
mirror = "main"

[params.widgets]
# header = ["breadcrumbs"]
homepage = ["recent_posts"]
sidebar = ["about","sidebar_menu","taxonomy_cloud","search"]
footer = ["social_menu", "search"]

[params.opengraph.facebook]
admins = [] # array of Facebook IDs
appID = ""
pageID = ""

[params.opengraph.twitter]
page = "" # Twitter page username

[params.seo]
# Title Separator: - – — · • * ⋆ | ~ « » < >
titleSeparator = "•"

[params.social]
# codepen = "MunifTanjim"
email = "jneeee@qq.com"
# facebook = "MunifTanjim"
github = "Jneeee"
# gitlab = "MunifTanjim"
# instagram = "MunifTanjim"
# linkedin = "muniftanjim"
# twitter = "MunifTanjim"
# telegram = "MunifTanjim"
# google_scholar = "qc6CJjYAAAAJ"
# youtube = "UCT-U0rNerYxItGcuoPX-WYA"

[params.comments]
enable = true

# Utterances: https://utteranc.es
[params.comments.utterances]
enable = false
issueTerm = "pathname" # pathname / url / title / og:title / <string>
label = ""
theme = "github-light"

[params.comments.utterances.github]
username = "jneeee"
repository = "blog"

[params.search]
client = "lunr" # algolia / fuse / lunr

[params.search.algolia]
appId = ""
indexName = ""
searchApiKey = ""

[taxonomies]
author = "authors"
category = "categories"
series = "series"
tag = "tags"

[permalinks]
page = "/:slug"
post = "/:year/:month/:title/index.html"

[blackfriday]
hrefTargetBlank = true

[languages]
# edit this block for your own language
[languages.zh]
lang = "zh"
languageName = "Chinese"
weight = 1
